const fetch = require('node-fetch');

const towns = [
  'Absam',
  'Achenkirch',
  'Achensee',
  'Aderklaa',
  'Admont',
  'Aggsbach',
  'Aigen-Schlägl',
  'Altaussee',
  'Alland',
  'Altach',
  'Altenmarkt im Pongau',
  'Amstetten',
  'Angern an der March',
  'Annaberg-Lungötz',
  'Attersee am Attersee',
  'Auersthal',
  'Axams',
  'Bad Aussee',
  'Bad Gastein',
  'Bad Goisern am Hallstättersee',
  'Bad Hall',
  'Bad Hofgastein',
  'Bad Ischl',
  'Bad Mitterndorf',
  'Bad Radkersburg',
  'Bad Schallerbach',
  'Bad Tatzmannsdorf',
  'Bad Vöslau',
  'Bad Waltersdorf',
  'Baden bei Wien',
  'Bergheim (Flachgau)',
  'Berndorf (Niederösterreich)',
  'Berwang',
  'Biberwier',
  'Bichlbach',
  'Bischofshofen',
  'Bludenz',
  'Bregenz',
  'Bödele',
  'Breitenfurt bei Wien',
  'Bruck an der Leitha',
  'Bruck an der Mur',
  'Bruckneudorf',
  'Brunn am Gebirge- Baden',
  'Damüls',
  'Deutsch Jahrndorf',
  'Deutsch-Wagram',
  'Deutschkreutz',
  'Deutschlandsberg',
  'Dienten am Hochkönig',
  'Dornbirn',
  'Dorfgastein',
  'Dürnkrut',
  'Dürnstein',
  'Ebbs',
  'Eben am Achensee',
  'Eben im Pongau',
  'Ebensee',
  'Ebreichsdorf',
  'Eckartsau',
  'Ehrwald',
  'Eisenstadt',
  'Elbigenalp',
  'Engelhartstetten',
  'Engelhartszell',
  'Enns',
  'Erl (Tirol)',
  'Erzberg',
  'Eisgarn',
  'Eggern',
  'Feldbach (Steiermark)',
  'Feldkirch',
  'Feldkirchen in Kärnten',
  'Filzmoos',
  'Finkenberg',
  'Finkenstein am Faaker See',
  'Fischamend',
  'Flachau',
  'Flattach',
  'Flughafen Graz',
  'Flughafen Salzburg',
  'Flughafen Wien-Schwechat',
  'Forchtenstein',
  'Forstau',
  'Frastanz',
  'Frauenkirchen',
  'Freistadt',
  'Fürstenfeld',
  'Fulpmes',
  'Fuschl am See',
  'Galtür',
  'Gänserndorf',
  'Garsten',
  'Gerasdorf bei Wien',
  'Gerlos',
  'Ginzling',
  'nas- Gmünd in Kärnten',
  'Gmünd (Niederösterreich)',
  'Goldegg im Pongau',
  'Gosau',
  'Göttweig',
  'Götzis',
  'Gramatneusiedl',
  'Gratwein-Straßengel',
  'Graz',
  'Grein',
  'Gries im Ötztal',
  'Gries im Sellrain',
  'Gröbming',
  'Grödig',
  'Groß-Enzersdorf',
  'Groß-Siegharts',
  'Großarl',
  'Großwarasdorf',
  'Gumpoldskirchen',
  'Guntramsdorf',
  'Gurk',
  'Güssing',
  'Hainburg an der Donau',
  'Hall in Tirol',
  'Hallein',
  'Hallstatt',
  'Hardegg',
  'Hartberg',
  'Haslau-Maria Ellend',
  'Heidenreichstein',
  'Heinfels',
  'Heiterwang',
  'Hermagor',
  'Hieflau',
  'Himberg',
  'Hinterbrühl',
  'Hintertux',
  'Hittisau',
  'Hochburg-Ach',
  'Hohe Wand',
  'Hohenau an der March',
  'Hohenems',
  'Hollabrunn',
  'Hopfgarten im Brixental',
  'Hörbranz',
  'Horn (Niederösterreich)',
  'Hüttau',
  'Hüttschlag',
  'Illmitz',
  'Imst',
  'Innervillgraten',
  'Innsbruck',
  'Innsbruck Airport',
  'Ischgl',
  'Jenbach',
  'Jennersdorf',
  'Johnsbach',
  'Judenburg',
  'Kaisers',
  'Kaltenbach',
  'Kaltenleutgeben',
  'Kapfenberg',
  'Kappl (Tirol)',
  'Kaprun',
  'Kartitsch',
  'Katschberg',
  'Kefermarkt',
  'Kirchberg in Tirol',
  'Kirchbichl',
  'Kirchdorf an der Krems',
  'Kittsee',
  'Kitzbühel',
  'Klagenfurt',
  'Klausen-Leopoldsdorf',
  'Kleinarl',
  'Klosterneuburg',
  'Knittelfeld',
  'Kolm Saigurn',
  'Korneuburg',
  'Krakautal',
  'Kramsach',
  'Krems an der Donau',
  'Kremsmünster',
  'Kufstein',
  'Laa an der Thaya',
  'Laab im Walde',
  'Lähn-Wengle',
  'Längenfeld',
  'Landeck (Tirol)',
  'Langen am Arlberg',
  'Lauterach',
  'Laxenburg',
  'Lermoos',
  'Leibnitz',
  'Leoben',
  'Leogang',
  'Leonding',
  'Leutasch',
  'Liechtensteinklamm',
  'Lienz',
  'Liezen',
  'Lilienfeld',
  'Linz',
  'Loipersdorf bei Fürstenfeld',
  'Lofer',
  'Loretto (Burgenland)',
  'Lustenau',
  'Marchegg',
  'Maria Alm am Steinernen Meer',
  'Maria Enzersdorf',
  'Mariazell',
  'Markgrafneusiedl',
  'Matrei am Brenner',
  'Mattersburg',
  'Mattsee',
  'Mauerbach',
  'Maurach (Achensee)',
  'Melk',
  'Mellau',
  'Mettmach',
  'Micheldorf',
  'Mistelbach (Niederösterreich)',
  'Mittelberg (Kleinwalsertal)',
  'Mittermeier an der Fischa',
  'Mittersill',
  'Molln',
  'Mödling',
  'Mondsee',
  'Moosbrunn',
  'Mühlbach am Hochkönig',
  'Murau',
  'Mürzzuschlag',
  'Nassereith',
  'Naturschutzgebiet Vilsalpsee',
  'Nenzing',
  'Neufeld an der Leitha',
  'Neumarkt am Wallersee',
  'Neunkirchen (Österreich)',
  'Neusiedl am See',
  'Neusiedler See',
  'Neustift im Stubaital',
  'Nickelsdorf',
  'Niederndorf',
  'Niedernsill',
  'Nußdorf am Attersee',
  'Oberalm',
  'Obergurgl',
  'Oberpullendorf',
  'Oberndorf bei Salzburg',
  'Obersiebenbrunn',
  'Obertauern',
  'Obertraun',
  'Oberwart',
  'Oetz',
  'Orth an der Donau',
  'Ossiacher See',
  'Pamhagen',
  'Perchtoldsdorf',
  'Pertisau',
  'Petronell-Carnuntum',
  'Pfarrwerfen',
  'Piesendorf',
  'Pinkafeld',
  'Poysdorf',
  'Pressbaum',
  'Puchberg am Schneeberg',
  'Purbach am Neusiedler See',
  'Purkersdorf',
  'Rinn',
  'Raasdorf',
  'Radfeld',
  'Radstadt',
  'Ramingstein',
  'Ramsau am Dachstein',
  'Rankweil',
  'Rattenberg',
  'Rauris',
  'Rax-Schneeberg-Gruppe',
  'Reisenberg',
  'Retz',
  'Reutte',
  'Ried im Innkreis',
  'Ried im Zillertal',
  'Riegersburg (Steiermark)',
  'Rohrau',
  'Rohrmoos-Untertal',
  'Rum (Tirol)',
  'Rust (Burgenland)',
  'Saalbach-Hinterglemm',
  'Saalfelden am Steinernen Meer',
  'Salzburg',
  'Sankt Andrä (Kärnten)',
  'Sankt Anton am Arlberg',
  'Sankt Gallen (Steiermark)',
  'Sankt Margarethen im Lungau',
  'Sankt Michael im Lungau',
  'Sankt Stefan im Rosental',
  'Sankt Veit an der Glan',
  'Sankt Veit im Pongau',
  'Scharndorf',
  'Scharnitz',
  'Scheibbs',
  'Schladming',
  'Schlitters',
  'Schmirntal',
  'Schörfling am Attersee',
  'Schrattenberg',
  'Schruns',
  'Schwarzach im Pongau',
  'Schwaz',
  'Schwechat',
  'See (Gemeinde)',
  'Seeboden am Millstätter See',
  'Seefeld in Tirol',
  'Seekirchen am Wallersee',
  'Seitenstetten',
  'Semmering',
  'Serfaus',
  'Shopping City Süd',
  'Siegendorf',
  'Sölden (Ötztal)',
  'Spittal an der Drau',
  'St. Christoph am Arlberg- St. Georgen im Attergau',
  'St. Gilgen',
  'St. Johann im Pongau',
  'St. Johann in Tirol',
  'St. Martin am Tennengebirge',
  'St. Pölten',
  'Stadl an der Mur',
  'Stadtschlaining',
  'Stans (Tirol)',
  'Stegersbach',
  'Steinbach am Attersee',
  'Steinberg am Rofan',
  'Steyr',
  'Stift Melk',
  'Stockerau',
  'Strasshof an der Nordbahn',
  'Strobl',
  'Stuben am Arlberg',
  'Stumm (Tirol)',
  'Sulz im Wienerwald',
  'Tarrenz',
  'Telfes im Stubai',
  'Telfs',
  'Ternitz',
  'Traiskirchen',
  'Tulfes',
  'Tulln an der Donau',
  'Turrach',
  'Unken',
  'Unterlamm',
  'Untersberg',
  'Untersiebenbrunn',
  'Untertauern',
  'Velden am Wörther See',
  'Vent',
  'Villach',
  'Vöcklabruck',
  'Vöcklamarkt',
  'Völs',
  'Vösendorf',
  'Vomp',
  'Wagrain',
  'Waidhofen an der Thaya',
  'Waidhofen an der Ybbs',
  'Wals-Siezenheim',
  'Warth (Vorarlberg)',
  'Wattens',
  'Weißenbach am Lech',
  'Weißensee (Kärnten)',
  'Weitra',
  'Weiz',
  'Wels',
  'Werfen',
  'Werfenweng',
  'Weyregg am Attersee',
  'Wien',
  'Wiener Neudorf',
  'Wiener Neustadt',
  'Wiesing',
  'Wolfgangsee',
  'Wolfsberg',
  'Wolfurt',
  'Wolkersdorf im Weinviertel',
  'Wörgl',
  'Ybbs an der Donau',
  'Zams',
  'Zell am Moos',
  'Zell am See',
  'Zell am Ziller',
  'Zirl',
  'Zistersdorf',
  'Zwettl',
  'Zürs',
];

const strapiUrl = 'http://localhost:1337/api/towns'; // Adjust this to match your collection's API endpoint

async function insertTowns() {
  for (const town of towns) {
    const response = await fetch(strapiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ data: { name: town } }),
    });

    if (!response.ok) {
      console.error(`Failed to insert town: ${town}`, await response.text());
    } else {
      console.log(`Successfully inserted town: ${town}`);
    }
  }
}

insertTowns();
